apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera-app-deploy
  namespace: ${GKE_NAMESPACE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caldera-app
  template:
    metadata:
      labels:
        app: caldera-app
    spec:
      containers:
      - name: caldera-app
        image: gcr.io/bigquery-poc-309702/caldera-server
        args:
          - /bin/sh
          - -c
          - |
            echo "Migrating the database before starting the server"
            django-admin migrate
            echo "Starting Gunicorn."
            exec gunicorn --bind 0.0.0.0:8000 caldera_server.wsgi
        env:
          - name: AUTHTIME_CLIENT_ID
            value: ${AUTHTIME_CLIENT_ID}
          - name: AUTHTIME_CLIENT_SECRET
            value: ${AUTHTIME_CLIENT_SECRET}
          - name: AUTHTIME_HOST
            value: ${AUTHTIME_HOST}
          - name: AUTHTIME_TOKEN_URI
            value: ${AUTHTIME_TOKEN_URI}
          - name: AUTHTIME_PROFILE_URI
            value: ${AUTHTIME_PROFILE_URI}
          - name: AUTHTIME_INVITATION_URI
            value: ${AUTHTIME_INVITATION_URI}
          - name: OAUTH_REDIRECT_URL
            value: ${OAUTH_REDIRECT_URL}
          - name: OAUTH_INVITER_ID
            value: ${OAUTH_INVITER_ID}
          - name: OAUTH_ORG_ID
            value: '${OAUTH_ORG_ID}'
          - name: CALDERA_SERVER_SECRET_KEY
            value: ${CALDERA_SERVER_SECRET_KEY}
          - name: SPARKPOST_API_KEY
            value: ${SPARKPOST_API_KEY}
          - name: DJANGO_SETTINGS_MODULE
            value: ${DJANGO_SETTINGS_MODULE}
          - name: CONTAINER_HTTP_PORT
            value: '${CONTAINER_HTTP_PORT}'
          - name: DB_HOST
            value: ${DATABASE_HOST}
          - name: DB_PORT
            value: '${DATABASE_PORT}'
          - name: DB_NAME
            value: ${DATABASE_NAME}
          - name: DB_USER
            value: ${DATABASE_USER}
          - name: DB_PASSWORD
            value: ${DATABASE_PASS}
      imagePullSecrets:
        - name: docker-auth-k8