apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caldera-app
  template:
    metadata:
      labels:
        app: caldera-app
    spec:
      containers:
      - name: caldera-app
        image: gcr.io/google-samples/node-hello:1.0
        env:
          - name: ENVAR1
            value: ${envar1}
          - name: ENVAR2
            value: ${envar2}